const products = [
  {
    id: 1,
    title: "Hamburger",
    subtitle: "Juicy and Tender",
    price: 5.99,
    image: "/burger.jpg",
    category: "Burgers",
  },
  {
    id: 2,
    title: "Cheese Burger",
    subtitle: "Extra Cheese",
    price: 6.99,
    image: "/cheeseburger.jpg",
    category: "Burgers",
  },
  {
    id: 3,
    title: "Cola Drink",
    subtitle: "Chilled",
    price: 0.60,
    image: "/cola.jpg",
    category: "Drinks",
  },
  {
    id: 4,
    title: "Orange Juice",
    subtitle: "Freshly Squeezed",
    price: 1.50,
    image: "/juice.jpg",
    category: "Drinks",
  },
  {
    id: 5,
    title: "Shawarma",
    subtitle: "Chicken Shawarma",
    price: 5.05,
    image: "/shuwarma.jpg",
    category: "Burgers",
  },
  {
    id: 6,
    title: "Pizza",
    subtitle: "Melted Cheese",
    price: 12.99,
    image: "/bizza.jpg",
    category: "Pizza",
  },
  {
    id: 7,
    title: "Pepperoni Pizza",
    subtitle: "Spicy Pepperoni",
    price: 8.50,
    image: "/peperoniBizza.jpg",
    category: "Pizza",
  },
  {
    id: 8,
    title: "Caesar Salad",
    subtitle: "Fresh and Crisp",
    price: 1.50,
    image: "/salad.jpeg",
    category: "Salads",
  },
  {
    id: 9,
    title: "Grilled Chicken",
    subtitle: "Tender and Flavorful",
    price: 9.99,
    image: "/chiken.jpg",
    category: "Grilled",
  },
  {
    id: 10,
    title: "Pasta Alfredo",
    subtitle: "Creamy Fettuccine",
    price: 9.80,
    image: "/bastaAlfredo.jpg",
    category: "Food",
  },
  {
    id: 12,
    title: "Chicken Biryani",
    subtitle: "Spicy and Savory",
    price: 9.50,
    image: "/chikenBIryani.jpg",
    category: "Food",
  },
];

export default products;
